Project/Models/ErrorViewModel.cs
using System;

namespace Project.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Project/Models/Potd.cs
using Newtonsoft.Json;

namespace Project.Models
{
    public class Potd
    {
        [JsonProperty("copyright")]
        public string CopyRight { get; set; }

        [JsonProperty("date")]
        public string Date { get; set; }

        [JsonProperty("explanation")]
        public string Explanation { get; set; }

        [JsonProperty("hdurl")]
        public string HDPicUrl { get; set; }

        [JsonProperty("media_type")]
        public string MediaType { get; set; }

        [JsonProperty("title")]
        public string PicTitle { get; set; }

        [JsonProperty("url")]
        public string NoramlPicUrl { get; set; }
    }
}

Project/Models/Solar.cs
namespace Project.Models
{
    public class Solar
    {
        public Solar()
        {
        }

        public int BodyID { get; set; }
        public string EnglishName { get; set; }
        public string TypeOf { get; set; }
        public string DistanceFrom { get; set; }
        public string Gravity { get; set; }
        public string AverageTemp { get; set; }
        public int Moons { get; set; }
        public string DiscoveredBy { get; set; }
    }
}

Project/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Project;
using Project.Models;
using System;
using System.Diagnostics;
using System.Threading.Tasks;

namespace Project.Controllers
{
    public class HomeController : Controller
    {
        private readonly NASAClient _client;

        public HomeController(NASAClient client)
        {
            _client = client;
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                var response = await _client.Get();
                return View(response);
            }
            catch (Exception)
            {

                throw;
            }
        }
        public IActionResult Login()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Project/Controllers/SolarController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Project;
using Project.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Project.Controllers
{
    public class SolarController : Controller
    {

        private readonly IPlanetRepo repo;
        public SolarController(IPlanetRepo repo)
        {
            this.repo = repo;
        }
        // GET: /<controller>/
        public IActionResult SolarIndex()
        {
            var planets = repo.GetAllPlanets();
            return View(planets);
        }

        public IActionResult ViewPlanet(int id)
        {
            var planet = repo.GetPlanet(id);
            return View(planet);
        }


        // updeate Section controller
        public IActionResult UpdateInfo(int id)
        {
            Solar bod = repo.GetPlanet(id);

            if (bod == null)
            {
                return View("Body Not Found");
            }
            return View(bod);
        }

        public IActionResult UpdateInfoToDataBase(Solar body)
        {
            repo.UpdateInfo(body);
            return RedirectToAction("ViewPlanet", new { id = body.BodyID });
        }

        // Create section of controller

        public IActionResult InsertBody()
        {

            return View();
        }

        public IActionResult InsertBodyIntoDatabase(Solar toBeAdded)
        {
            repo.AddSolarBody(toBeAdded);
            return RedirectToAction("SolarIndex");
        }

        public IActionResult RemoveBody(Solar body)
        {
            repo.RemoveBody(body);
            return RedirectToAction("SolarIndex");
        }

        public IActionResult ShowSearchResults(string SearchPhrase)
        {
            var filteredSolars = repo.SearchedSolar(SearchPhrase);
            return View(filteredSolars);
        }
    }
}

Project/Views/Home/Index.cshtml
@model Potd

@{
    ViewData["Title"] = "Home";
}

<br />
<div class="text-center">
    <h1 class="display-4"> Solar Database </h1>
    <br />
    <form id="search-form" class="form-inline my-2 my-lg-0">
        <div class="input-group mb-2 mr-sm-2">
            <input id="search-field"class="form-control mr-sm-2" type="search" placeholder="search database" aria-label="Search" name="SearchPhrase">
            <button id="search-button" asp-action="ShowSearchResults" asp-controller="Solar" class="btn btn-outline-success my-2 my-sm-0" type="submit" value="Search">Search</button>
        </div>
    </form>
    <br />
    <p class="N_title">@Model.PicTitle</p>
    <p class="N_paragraph">@Model.Explanation</p>
    <p class="N_copyright">@Model.CopyRight</p>
    <img class="N_img" src="@Model.NoramlPicUrl" alt="LINK BROKEN" />
</div>
<br />

Project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Solar Database </title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/NASA_Project.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="http://fonts.cdnfonts.com/css/bambi" />
</head>

<body>
    <header>
        <nav class="top-nav">
            <h1 class="logo"></h1>
            <ul>
                <li class="bar"><a asp-controller="Home" asp-action="Index">HOME</a></li>
                <li class="bar"><a asp-controller="Solar" asp-action="SolarIndex">DATABASE</a></li>
                <li class="bar"><a href="https://coreyareid.github.io/">PORTFOLIO PAGE</a></li>
                <li><button class="li-button" onclick="document.getElementById('id01').style.display='block'">LOGIN</button></li>
            </ul>
        </nav>

        <!--Modal-->
        <div id="id01" class="modal">

            <!--Modal Container-->
            <form class="modal-content animate" action="/action_page.php">
                <div class="container">
                    <label for="uname"><b>Username</b></label>
                    <input type="text" placeholder="Enter Username" name="uname" required>

                    <label for="psw"><b>Password</b></label>
                    <input type="password" placeholder="Enter Password" name="psw" required>

                    <button class="li-button" type="submit">Login</button>
                    <p class="log-modal"><b class="wng">Warning:</b> Trying to actually login will crash the website. (Work in progress)</p>
                </div>
            </form>
        </div>
    </header>
    <br />
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <br />
    <footer class="footer">
        <div class="footer-container">
            &copy; 2022 - Project - Corey Reid
        </div>
    </footer>

    <script> //Modal script
        var modal = document.getElementById('id01');
        window.onclick = function (event)
        {
            if (event.target == modal)
            {
                modal.style.display = "none";
            }
        }
    </script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>

Project/Views/Solar/InsertBody.cshtml
@model Solar

<br />
<h2> Add a Solar Body</h2>
<div class="form-container">
    @using (Html.BeginForm("InsertBodyIntoDatabase", "Solar", "Post"))
     {
        <label asp-for="EnglishName" class="control-label">English Name</label>
        <input type="text" name="EnglishName" class="form-control" />

        <label asp-for="TypeOf" class="control-label">Type of Body</label>
        <input type="text" name="TypeOf" class="form-control" />

        <label asp-for="DistanceFrom" class="control-label">Distance from the Sun</label>
        <input type="text" name="DistanceFrom" class="form-control" />

        <label asp-for="Gravity" class="control-label">Gravity</label>
        <input type="text" name="Gravity" class="form-control" />

        <label asp-for="AverageTemp" class="control-label">Average Temperature</label>
        <input type="text" name="AverageTemp" class="form-control" />

        <label asp-for="Moons" class="control-label">Moons</label>
        <input type="number" name="Moons" class="form-control" />

        <label asp-for="DiscoveredBy" class="control-label">Discovered By</label>
        <input type="text" name="DiscoveredBy" class="form-control" />

        <br />
        <input id="w_button" class="w_item" type="submit" value="Create Solar" />
    }
</div>
<br />

Project/Views/Solar/ShowSearchResults.cshtml
@model IEnumerable<Solar>

@{
    ViewData["Title"] = "DATABASE";
}

<br />

@foreach (var body in Model)
{
    <h2>@body.EnglishName</h2>
}

<table class="table">
    <tr>
        <th class="t_header">Type of Body</th>
        <th class="t_header">Distance from Sun</th>
        <th class="t_header">Gravity</th>
        <th class="t_header">Average Temperature</th>
        <th class="t_header">Moons</th>
        <th class="t_header">Discovered By</th>
    </tr>

    @foreach (var body in Model)
    {
        <tr>
            <td id="t_data" class="t_Type">@body.TypeOf</td>
            <td id="t_data" class="t_Distance">@body.DistanceFrom</td>
            <td id="t_data" class="t_Gravity">@body.Gravity</td>
            <td id="t_data" class="t_Temp">@body.AverageTemp</td>
            <td id="t_data" class="t_Moons">@body.Moons</td>
            <td id="t_data" class="t_Discovered">@body.DiscoveredBy</td>
        </tr>
    }
</table>

<div class="img-container">

    @foreach (var body in Model)
    {
        @switch (body.EnglishName)
        {
            case "Mercury":
                <img class="s-image" src="https://solarsystem.nasa.gov/system/resources/detail_files/771_PIA16853.jpg" />
                break;

            case "Venus":
                <img class="s-image" src="https://solarsystem.nasa.gov/system/resources/detail_files/688_Venus.jpg" />
                break;

            case "Earth":
                <img class="s-image" src="https://www.nasa.gov/sites/default/files/styles/full_width_feature/public/thumbnails/image/187_1003705_americas_dxm.png" />
                break;

            case "Mars":
                <img class="s-image" src="https://mars.nasa.gov/system/news_items/main_images/8888_mars20130708-web.jpg" />
                break;

            case "Jupiter":
                <img class="s-image" src="https://solarsystem.nasa.gov/system/resources/detail_files/2486_stsci-h-p1936a_1800.jpg" />
                break;

            case "Saturn":
                <img class="s-image" src="https://solarsystem.nasa.gov/system/resources/detail_files/2490_stsci-h-p1943a-f_1200.jpg" />
                break;

            case "Uranus":
                <img class="s-image" src="https://solarsystem.nasa.gov/system/resources/detail_files/599_PIA18182.jpg" />
                break;

            case "Neptune":
                <img class="s-image" src="https://solarsystem.nasa.gov/system/resources/detail_files/768_oct_1_2015_flare.jpg" />
                break;

            case "Pluto":
                <img class="s-image" src="https://solarsystem.nasa.gov/system/resources/detail_files/933_BIG_P_COLOR_2_TRUE_COLOR1_1980.jpg" />
                break;

            case "Sun":
                <img class="s-image" src="https://solarsystem.nasa.gov/system/resources/detail_files/476_VenusTransitApproach1200w.jpg" />
                break;
        }
    }
</div>

Project/Views/Solar/SolarIndex.cshtml
@model IEnumerable<Solar>

@{
    ViewData["Title"] = "DATABASE";
}

<br />
<h2> SOLAR BODIES </h2>

<p>Click on BodyID number for individual information.</p>
<table class="table">
    <tr>
        <th class="t_header">BodyID</th>
        <th class="t_header">English Name</th>
        <th class="t_header">Type of Body</th>
        <th class="t_header">Distance from Sun</th>
        <th class="t_header">Gravity</th>
        <th class="t_header">Average Temperature</th>
        <th class="t_header">Moons</th>
        <th class="t_header">Discovered By</th>
    </tr>

    @foreach (var body in Model)
        {

            <tr>
                <td id="t_data" class="t_ID"><a href="/Solar/ViewPlanet/@body.BodyID">@body.BodyID</a></td>
                <td id="t_data" class="t_Name">@body.EnglishName</td>
                <td id="t_data" class="t_Type">@body.TypeOf</td>
                <td id="t_data" class="t_Distance">@body.DistanceFrom</td>
                <td id="t_data" class="t_Gravity">@body.Gravity</td>
                <td id="t_data" class="t_Temp">@body.AverageTemp</td>
                <td id="t_data" class="t_Moons">@body.Moons</td>
                <td id="t_data" class="t_Discovered">@body.DiscoveredBy</td>
            </tr>
        }
</table>

<div class="form-container" style="display: block">
    <a class="w_item" href="/Solar/InsertBody"> Add A Discovered Solar Body</a>
</div>
<br />

Project/Views/Solar/UpdateInfo.cshtml
@model Solar

<br />
<h2>Update @Model.EnglishName</h2>
<div class="form-container">
    @using (Html.BeginForm("UpdateInfoToDatabase", "Solar", "Post"))
    {
        <input asp-for="BodyID" type="hidden" value="@Model.BodyID" />

        <label asp-for="EnglishName" class="control-label">EnglishName</label>
        <input type="text" name="EnglishName" class="form-control" value="@Model.EnglishName" />

        <label asp-for="TypeOf" class="control-label">Type of Body</label>
        <input type="text" name="TypeOf" class="form-control" value="@Model.TypeOf" />

        <label asp-for="DistanceFrom" class="control-label">Distance From</label>
        <input type="text" name="DistanceFrom" class="form-control" value="@Model.DistanceFrom" />

        <label asp-for="Gravity" class="control-label">Gravity</label>
        <input type="text" name="Gravity" class="form-control" value="@Model.Gravity" />

        <label asp-for="AverageTemp" class="control-label">Average Temperature</label>
        <input type="text" name="AverageTemp" class="form-control" value="@Model.AverageTemp" />

        <label asp-for="Moons" class="control-label">Moons</label>
        <input type="number" step="0.01" name="Moons" class="form-control" value="@Model.Moons" />

        <label asp-for="DiscoveredBy" class="control-label">Discovered By</label>
        <input type="text" name="DiscoveredBy" class="form-control" value="@Model.DiscoveredBy" />

        <br />
        <input id="w_button" class="w_item" type="submit" value="Update Solar" />
    }

</div>
<br />

Project/Views/Solar/ViewPlanet.cshtml
@model Solar

<br />
<h3>@Model.EnglishName</h3>

<table class="table">

    <tr>
        <th class="t_header">Type of Body</th>
        <th class="t_header">Distance From Sun</th>
        <th class="t_header">Gravity</th>
        <th class="t_header">Average Temperature</th>
        <th class="t_header">Moons</th>
        <th class="t_header">Discovered By</th>
    </tr>
    <tr>
        <td id="t_data" class="t_Type">@Model.TypeOf</td>
        <td id="t_data" class="t_Distance">@Model.DistanceFrom</td>
        <td id="t_data" class="t_Gravity">@Model.Gravity</td>
        <td id="t_data" class="t_Temp">@Model.AverageTemp</td>
        <td id="t_data" class="t_Moons">@Model.Moons</td>
        <td id="t_data" class="t_Discovered">@Model.DiscoveredBy</td>
    </tr>
</table>

<div class="img-container">
    @switch (Model.EnglishName)
    {
        case "Mercury":
            <img class="s-image" src="https://solarsystem.nasa.gov/system/resources/detail_files/771_PIA16853.jpg" />
            break;

        case "Venus":
            <img class="s-image" src="https://solarsystem.nasa.gov/system/resources/detail_files/688_Venus.jpg" />
            break;

        case "Earth":
            <img class="s-image" src="https://www.nasa.gov/sites/default/files/styles/full_width_feature/public/thumbnails/image/187_1003705_americas_dxm.png" />
            break;

        case "Mars":
            <img class="s-image" src="https://mars.nasa.gov/system/news_items/main_images/8888_mars20130708-web.jpg" />
            break;

        case "Jupiter":
            <img class="s-image" src="https://solarsystem.nasa.gov/system/resources/detail_files/2486_stsci-h-p1936a_1800.jpg" />
            break;

        case "Saturn":
            <img class="s-image" src="https://solarsystem.nasa.gov/system/resources/detail_files/2490_stsci-h-p1943a-f_1200.jpg" />
            break;

        case "Uranus":
            <img class="s-image" src="https://solarsystem.nasa.gov/system/resources/detail_files/599_PIA18182.jpg" />
            break;

        case "Neptune":
            <img class="s-image" src="https://solarsystem.nasa.gov/system/resources/detail_files/768_oct_1_2015_flare.jpg" />
            break;

        case "Pluto":
            <img class="s-image" src="https://solarsystem.nasa.gov/system/resources/detail_files/933_BIG_P_COLOR_2_TRUE_COLOR1_1980.jpg" />
            break;

        case "Sun":
            <img class="s-image" src="https://solarsystem.nasa.gov/system/resources/detail_files/476_VenusTransitApproach1200w.jpg" />
            break;
    }
</div>

<nav class="planet-nav">
    <ul>
        <li class="bar2">
            <a class="w_item" href="/Solar/UpdateInfo/@Model.BodyID">Update Solar Body</a>
        </li>

        <li class="bar2">
            @using (Html.BeginForm("RemoveBody", "Solar", "Post"))
            {
                <input type="hidden" asp-for="BodyID" value="@Model.BodyID" />
                <input class="w_item " id="w_button" type="submit" onclick="return confirm('Ensure solar body information is incorrect before deleting from the database')"
                       value="Remove solar Body" />
            }
        </li>
    </ul>
</nav>
<br />